name: E2E Tests por Tags

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
          cache: 'npm'
      - run: npm ci
      - run: npm run test:api

  e2e-login:
    runs-on: ubuntu-latest
    needs: api-tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
          cache: 'npm'
      - run: npm ci
      - name: Cypress Login
        uses: cypress-io/github-action@v6
        with:
          wait-on: 'https://automationexercise.com'
          wait-on-timeout: 120
          browser: chrome
        env:
          CYPRESS_TAGS: '@login_sucesso,@login_erro'

  e2e-cadastro:
    runs-on: ubuntu-latest
    needs: api-tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Cypress Cadastro
        uses: cypress-io/github-action@v6
        with:
          wait-on: 'https://automationexercise.com'
          wait-on-timeout: 120
        env:
          CYPRESS_TAGS: '@cadastro'

  e2e-carrinho:
    runs-on: ubuntu-latest
    needs: api-tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
          cache: 'npm'
      - run: npm ci
      - name: Cypress Carrinho
        uses: cypress-io/github-action@v6
        with:
          wait-on: 'https://automationexercise.com'
          wait-on-timeout: 120
        env:
          CYPRESS_TAGS: '@carrinho'

  reports:
    needs: [e2e-login, e2e-cadastro, e2e-carrinho]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: mochawesome-reports
          path: cypress/reports/
